server:
  port: 2001
spring:
  application:
    name: jingyue-oauth
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: jingyue-oauth2001
    prefer-ip-address: true

info:
  app.name: 认证服务
  company.name: www.jingyues.com
  build.artifactId: jingyue-oauth
  build.version: V1.0
  build.company: 京跃科技有限公司
