server:
  port: 9002
#开启熔断机制
#feign:
  #hystrix:
    #enabled: true

spring:
  application:
    name: jingyue-consumer-feign
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: jingyue-consumer-feign
    prefer-ip-address: true
info:
  app.name: jingyue-consumer-feign
  company.name: 得逸信息技术有限公司
  address.name: 湖北省十堰市
  contry.name: china
