server:
  port: 8080
#数据源
spring:
  application:
    name: jingyue-user
  datasource:
    url: jdbc:mysql://localhost:3306/jingyue?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: lipsadmin
    driver-class-name: com.mysql.jdbc.Driver
  jmx:
    default-domain: jingyue-user
#配置mybatis
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
  type-aliases-package: com.jingyue.api.pojo


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: jingyue-user
    prefer-ip-address: true
info:
  app.name: 用户模块
  company.name: 得逸信息技术有限公司
  address.name: 湖北省十堰市
  contry.name: china

#logging:
    #pattern:
  #console: '%d -%msg%n'
  #path: D:/data/log/seller.log
    #level:
  #root: info
#日志级别
logging:
  level:
    com:
      jingyue:
        user:
          mapper: info