server:
  port: 6001
#http://gateway-6001.com:6001/jingyue-dept/dept/2 加上网管的访问地址
#gateway-6001.com:6001网关绑定主机地址的名称
#/dept/2 Controller访问的jingyue-dept提供方对应的地址
#jingyue-dept服务提供者的名称
spring:
  application:
    name: jingyue-zuul6001
#http://gateway-6001.com:6001/jingyue/mydept/dept/2 加上网管的访问地址
zuul:
  #ignored-services: microservicecloud-dept
  prefix: /jingyue
  ignored-services: "*"
  routes:
    mydept.serviceId: jingyue-dept
    mydept.path: /mydept/**
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-6001.com
    prefer-ip-address: true

info:
  app.name: jingyue-zuul
  company.name: www.jingyues.com
  build.artifactId: jingyue-zuul
  build.version: V1.0
  build.company: 京跃科技有限公司

